theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: false
  logo:
    header: /assets/images/logo.jpeg
    footer: /assets/images/logo.jpeg
  events:
    index:
      truncate_description: 0
  pages:
    index:
      truncate_description: 0
  posts:
    index:
      truncate_description: 0
