[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/agenda/2023-12-05-forum-des-plateformes-cooperatives-2023/"
to = "/agenda/2023/forum-des-plateformes-cooperatives-2023/"

[[redirects]]
from = "/actualites/2023-11-16-une-approche-par-les-communs-avec-les-collectivites-locales-pour-une-transition-ecologique-et-solidaire/"
to = "/actualites/2023-11-16-une-approche-par-les-communs-avec-les-collectivites-locales-pour-une-transition-ecologique-et-solida/"

